#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 131
#define ALIAS_COUNT 0
#define TOKEN_COUNT 114
#define EXTERNAL_TOKEN_COUNT 106
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_COLON = 4,
  anon_sym_COLON_EQ = 5,
  sym_comment = 6,
  sym_tool_directive = 7,
  sym_identifier = 8,
  sym_after = 9,
  sym_alias = 10,
  sym_all = 11,
  sym_architecture = 12,
  sym_array = 13,
  sym_assert = 14,
  sym_attribute = 15,
  sym_begin = 16,
  sym_block = 17,
  sym_buffer = 18,
  sym_bus = 19,
  sym_case = 20,
  sym_component = 21,
  sym_configuration = 22,
  sym_constant = 23,
  sym_context = 24,
  sym_default = 25,
  sym_disconnect = 26,
  sym_downto = 27,
  sym_else = 28,
  sym_elsif = 29,
  sym_end = 30,
  sym_entity = 31,
  sym_exit = 32,
  sym_file = 33,
  sym_for = 34,
  sym_force = 35,
  sym_function = 36,
  sym_generate = 37,
  sym_generic = 38,
  sym_group = 39,
  sym_guarded = 40,
  sym_if = 41,
  sym_impure = 42,
  sym_in = 43,
  sym_inertial = 44,
  sym_inout = 45,
  sym_is = 46,
  sym_label = 47,
  sym_library = 48,
  sym_linkage = 49,
  sym_literal = 50,
  sym_loop = 51,
  sym_map = 52,
  sym_new = 53,
  sym_next = 54,
  sym_null = 55,
  sym_of = 56,
  sym_on = 57,
  sym_open = 58,
  sym_others = 59,
  sym_out = 60,
  sym_package = 61,
  sym_parameter = 62,
  sym_port = 63,
  sym_postponed = 64,
  sym_procedure = 65,
  sym_process = 66,
  sym_property = 67,
  sym_protected = 68,
  sym_pure = 69,
  sym_range = 70,
  sym_record = 71,
  sym_register = 72,
  sym_reject = 73,
  sym_release = 74,
  sym_report = 75,
  sym_return = 76,
  sym_select = 77,
  sym_sequence = 78,
  sym_severity = 79,
  sym_shared = 80,
  sym_signal = 81,
  sym_subtype = 82,
  sym_then = 83,
  sym_transport = 84,
  sym_type = 85,
  sym_unaffected = 86,
  sym_units = 87,
  sym_until = 88,
  sym_use = 89,
  sym_variable = 90,
  sym_vunit = 91,
  sym_wait = 92,
  sym_when = 93,
  sym_while = 94,
  sym_with = 95,
  sym_attribute_function = 96,
  sym_attribute_pure_function = 97,
  sym_attribute_range = 98,
  sym_attribute_signal = 99,
  sym_attribute_subtype = 100,
  sym_attribute_type = 101,
  sym_attribute_value = 102,
  sym_builtin_function = 103,
  sym_builtin_type = 104,
  sym_operator_adding = 105,
  sym_operator_condition = 106,
  sym_operator_logical = 107,
  sym_operator_miscellaneous = 108,
  sym_operator_multiplying = 109,
  sym_operator_relational = 110,
  sym_operator_shift = 111,
  sym_operator_sign = 112,
  sym_error_sentinel = 113,
  sym_source_file = 114,
  sym_entity_declaration = 115,
  sym_formal_port_clause = 116,
  sym_interface_list = 117,
  sym_interface_declaration = 118,
  sym_interface_object_declaration = 119,
  sym_interface_signal_declaration = 120,
  sym_identifier_list = 121,
  sym_mode = 122,
  sym_subtype_indication = 123,
  sym_resolution_indication = 124,
  sym_type_mark = 125,
  sym_expression = 126,
  sym_entity_statement_part = 127,
  sym_entity_simple_name = 128,
  aux_sym_interface_list_repeat1 = 129,
  aux_sym_identifier_list_repeat1 = 130,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_COLON_EQ] = ":=",
  [sym_comment] = "comment",
  [sym_tool_directive] = "tool_directive",
  [sym_identifier] = "identifier",
  [sym_after] = "after",
  [sym_alias] = "alias",
  [sym_all] = "all",
  [sym_architecture] = "architecture",
  [sym_array] = "array",
  [sym_assert] = "assert",
  [sym_attribute] = "attribute",
  [sym_begin] = "begin",
  [sym_block] = "block",
  [sym_buffer] = "buffer",
  [sym_bus] = "bus",
  [sym_case] = "case",
  [sym_component] = "component",
  [sym_configuration] = "configuration",
  [sym_constant] = "constant",
  [sym_context] = "context",
  [sym_default] = "default",
  [sym_disconnect] = "disconnect",
  [sym_downto] = "downto",
  [sym_else] = "else",
  [sym_elsif] = "elsif",
  [sym_end] = "end",
  [sym_entity] = "entity",
  [sym_exit] = "exit",
  [sym_file] = "file",
  [sym_for] = "for",
  [sym_force] = "force",
  [sym_function] = "function",
  [sym_generate] = "generate",
  [sym_generic] = "generic",
  [sym_group] = "group",
  [sym_guarded] = "guarded",
  [sym_if] = "if",
  [sym_impure] = "impure",
  [sym_in] = "in",
  [sym_inertial] = "inertial",
  [sym_inout] = "inout",
  [sym_is] = "is",
  [sym_label] = "label",
  [sym_library] = "library",
  [sym_linkage] = "linkage",
  [sym_literal] = "literal",
  [sym_loop] = "loop",
  [sym_map] = "map",
  [sym_new] = "new",
  [sym_next] = "next",
  [sym_null] = "null",
  [sym_of] = "of",
  [sym_on] = "on",
  [sym_open] = "open",
  [sym_others] = "others",
  [sym_out] = "out",
  [sym_package] = "package",
  [sym_parameter] = "parameter",
  [sym_port] = "port",
  [sym_postponed] = "postponed",
  [sym_procedure] = "procedure",
  [sym_process] = "process",
  [sym_property] = "property",
  [sym_protected] = "protected",
  [sym_pure] = "pure",
  [sym_range] = "range",
  [sym_record] = "record",
  [sym_register] = "register",
  [sym_reject] = "reject",
  [sym_release] = "release",
  [sym_report] = "report",
  [sym_return] = "return",
  [sym_select] = "select",
  [sym_sequence] = "sequence",
  [sym_severity] = "severity",
  [sym_shared] = "shared",
  [sym_signal] = "signal",
  [sym_subtype] = "subtype",
  [sym_then] = "then",
  [sym_transport] = "transport",
  [sym_type] = "type",
  [sym_unaffected] = "unaffected",
  [sym_units] = "units",
  [sym_until] = "until",
  [sym_use] = "use",
  [sym_variable] = "variable",
  [sym_vunit] = "vunit",
  [sym_wait] = "wait",
  [sym_when] = "when",
  [sym_while] = "while",
  [sym_with] = "with",
  [sym_attribute_function] = "attribute_function",
  [sym_attribute_pure_function] = "attribute_pure_function",
  [sym_attribute_range] = "attribute_range",
  [sym_attribute_signal] = "attribute_signal",
  [sym_attribute_subtype] = "attribute_subtype",
  [sym_attribute_type] = "attribute_type",
  [sym_attribute_value] = "attribute_value",
  [sym_builtin_function] = "builtin_function",
  [sym_builtin_type] = "builtin_type",
  [sym_operator_adding] = "operator_adding",
  [sym_operator_condition] = "operator_condition",
  [sym_operator_logical] = "operator_logical",
  [sym_operator_miscellaneous] = "operator_miscellaneous",
  [sym_operator_multiplying] = "operator_multiplying",
  [sym_operator_relational] = "operator_relational",
  [sym_operator_shift] = "operator_shift",
  [sym_operator_sign] = "operator_sign",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_entity_declaration] = "entity_declaration",
  [sym_formal_port_clause] = "formal_port_clause",
  [sym_interface_list] = "interface_list",
  [sym_interface_declaration] = "interface_declaration",
  [sym_interface_object_declaration] = "interface_object_declaration",
  [sym_interface_signal_declaration] = "interface_signal_declaration",
  [sym_identifier_list] = "identifier_list",
  [sym_mode] = "mode",
  [sym_subtype_indication] = "subtype_indication",
  [sym_resolution_indication] = "resolution_indication",
  [sym_type_mark] = "type_mark",
  [sym_expression] = "expression",
  [sym_entity_statement_part] = "entity_statement_part",
  [sym_entity_simple_name] = "entity_simple_name",
  [aux_sym_interface_list_repeat1] = "interface_list_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_comment] = sym_comment,
  [sym_tool_directive] = sym_tool_directive,
  [sym_identifier] = sym_identifier,
  [sym_after] = sym_after,
  [sym_alias] = sym_alias,
  [sym_all] = sym_all,
  [sym_architecture] = sym_architecture,
  [sym_array] = sym_array,
  [sym_assert] = sym_assert,
  [sym_attribute] = sym_attribute,
  [sym_begin] = sym_begin,
  [sym_block] = sym_block,
  [sym_buffer] = sym_buffer,
  [sym_bus] = sym_bus,
  [sym_case] = sym_case,
  [sym_component] = sym_component,
  [sym_configuration] = sym_configuration,
  [sym_constant] = sym_constant,
  [sym_context] = sym_context,
  [sym_default] = sym_default,
  [sym_disconnect] = sym_disconnect,
  [sym_downto] = sym_downto,
  [sym_else] = sym_else,
  [sym_elsif] = sym_elsif,
  [sym_end] = sym_end,
  [sym_entity] = sym_entity,
  [sym_exit] = sym_exit,
  [sym_file] = sym_file,
  [sym_for] = sym_for,
  [sym_force] = sym_force,
  [sym_function] = sym_function,
  [sym_generate] = sym_generate,
  [sym_generic] = sym_generic,
  [sym_group] = sym_group,
  [sym_guarded] = sym_guarded,
  [sym_if] = sym_if,
  [sym_impure] = sym_impure,
  [sym_in] = sym_in,
  [sym_inertial] = sym_inertial,
  [sym_inout] = sym_inout,
  [sym_is] = sym_is,
  [sym_label] = sym_label,
  [sym_library] = sym_library,
  [sym_linkage] = sym_linkage,
  [sym_literal] = sym_literal,
  [sym_loop] = sym_loop,
  [sym_map] = sym_map,
  [sym_new] = sym_new,
  [sym_next] = sym_next,
  [sym_null] = sym_null,
  [sym_of] = sym_of,
  [sym_on] = sym_on,
  [sym_open] = sym_open,
  [sym_others] = sym_others,
  [sym_out] = sym_out,
  [sym_package] = sym_package,
  [sym_parameter] = sym_parameter,
  [sym_port] = sym_port,
  [sym_postponed] = sym_postponed,
  [sym_procedure] = sym_procedure,
  [sym_process] = sym_process,
  [sym_property] = sym_property,
  [sym_protected] = sym_protected,
  [sym_pure] = sym_pure,
  [sym_range] = sym_range,
  [sym_record] = sym_record,
  [sym_register] = sym_register,
  [sym_reject] = sym_reject,
  [sym_release] = sym_release,
  [sym_report] = sym_report,
  [sym_return] = sym_return,
  [sym_select] = sym_select,
  [sym_sequence] = sym_sequence,
  [sym_severity] = sym_severity,
  [sym_shared] = sym_shared,
  [sym_signal] = sym_signal,
  [sym_subtype] = sym_subtype,
  [sym_then] = sym_then,
  [sym_transport] = sym_transport,
  [sym_type] = sym_type,
  [sym_unaffected] = sym_unaffected,
  [sym_units] = sym_units,
  [sym_until] = sym_until,
  [sym_use] = sym_use,
  [sym_variable] = sym_variable,
  [sym_vunit] = sym_vunit,
  [sym_wait] = sym_wait,
  [sym_when] = sym_when,
  [sym_while] = sym_while,
  [sym_with] = sym_with,
  [sym_attribute_function] = sym_attribute_function,
  [sym_attribute_pure_function] = sym_attribute_pure_function,
  [sym_attribute_range] = sym_attribute_range,
  [sym_attribute_signal] = sym_attribute_signal,
  [sym_attribute_subtype] = sym_attribute_subtype,
  [sym_attribute_type] = sym_attribute_type,
  [sym_attribute_value] = sym_attribute_value,
  [sym_builtin_function] = sym_builtin_function,
  [sym_builtin_type] = sym_builtin_type,
  [sym_operator_adding] = sym_operator_adding,
  [sym_operator_condition] = sym_operator_condition,
  [sym_operator_logical] = sym_operator_logical,
  [sym_operator_miscellaneous] = sym_operator_miscellaneous,
  [sym_operator_multiplying] = sym_operator_multiplying,
  [sym_operator_relational] = sym_operator_relational,
  [sym_operator_shift] = sym_operator_shift,
  [sym_operator_sign] = sym_operator_sign,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_entity_declaration] = sym_entity_declaration,
  [sym_formal_port_clause] = sym_formal_port_clause,
  [sym_interface_list] = sym_interface_list,
  [sym_interface_declaration] = sym_interface_declaration,
  [sym_interface_object_declaration] = sym_interface_object_declaration,
  [sym_interface_signal_declaration] = sym_interface_signal_declaration,
  [sym_identifier_list] = sym_identifier_list,
  [sym_mode] = sym_mode,
  [sym_subtype_indication] = sym_subtype_indication,
  [sym_resolution_indication] = sym_resolution_indication,
  [sym_type_mark] = sym_type_mark,
  [sym_expression] = sym_expression,
  [sym_entity_statement_part] = sym_entity_statement_part,
  [sym_entity_simple_name] = sym_entity_simple_name,
  [aux_sym_interface_list_repeat1] = aux_sym_interface_list_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_after] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_all] = {
    .visible = true,
    .named = true,
  },
  [sym_architecture] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_assert] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_buffer] = {
    .visible = true,
    .named = true,
  },
  [sym_bus] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_configuration] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_default] = {
    .visible = true,
    .named = true,
  },
  [sym_disconnect] = {
    .visible = true,
    .named = true,
  },
  [sym_downto] = {
    .visible = true,
    .named = true,
  },
  [sym_else] = {
    .visible = true,
    .named = true,
  },
  [sym_elsif] = {
    .visible = true,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_exit] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_for] = {
    .visible = true,
    .named = true,
  },
  [sym_force] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_generate] = {
    .visible = true,
    .named = true,
  },
  [sym_generic] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_guarded] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_impure] = {
    .visible = true,
    .named = true,
  },
  [sym_in] = {
    .visible = true,
    .named = true,
  },
  [sym_inertial] = {
    .visible = true,
    .named = true,
  },
  [sym_inout] = {
    .visible = true,
    .named = true,
  },
  [sym_is] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_library] = {
    .visible = true,
    .named = true,
  },
  [sym_linkage] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_new] = {
    .visible = true,
    .named = true,
  },
  [sym_next] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_of] = {
    .visible = true,
    .named = true,
  },
  [sym_on] = {
    .visible = true,
    .named = true,
  },
  [sym_open] = {
    .visible = true,
    .named = true,
  },
  [sym_others] = {
    .visible = true,
    .named = true,
  },
  [sym_out] = {
    .visible = true,
    .named = true,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_postponed] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_process] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_protected] = {
    .visible = true,
    .named = true,
  },
  [sym_pure] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_reject] = {
    .visible = true,
    .named = true,
  },
  [sym_release] = {
    .visible = true,
    .named = true,
  },
  [sym_report] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_select] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_severity] = {
    .visible = true,
    .named = true,
  },
  [sym_shared] = {
    .visible = true,
    .named = true,
  },
  [sym_signal] = {
    .visible = true,
    .named = true,
  },
  [sym_subtype] = {
    .visible = true,
    .named = true,
  },
  [sym_then] = {
    .visible = true,
    .named = true,
  },
  [sym_transport] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_unaffected] = {
    .visible = true,
    .named = true,
  },
  [sym_units] = {
    .visible = true,
    .named = true,
  },
  [sym_until] = {
    .visible = true,
    .named = true,
  },
  [sym_use] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_vunit] = {
    .visible = true,
    .named = true,
  },
  [sym_wait] = {
    .visible = true,
    .named = true,
  },
  [sym_when] = {
    .visible = true,
    .named = true,
  },
  [sym_while] = {
    .visible = true,
    .named = true,
  },
  [sym_with] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_function] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_pure_function] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_range] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_signal] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_subtype] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_type] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_function] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_adding] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_logical] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_miscellaneous] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_multiplying] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_relational] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_shift] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_formal_port_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_list] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_object_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_signal_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_subtype_indication] = {
    .visible = true,
    .named = true,
  },
  [sym_resolution_indication] = {
    .visible = true,
    .named = true,
  },
  [sym_type_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_statement_part] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_simple_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_interface_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '`') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_tool_directive);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 4},
  [5] = {.lex_state = 0, .external_lex_state = 4},
  [6] = {.lex_state = 1, .external_lex_state = 5},
  [7] = {.lex_state = 0, .external_lex_state = 6},
  [8] = {.lex_state = 0, .external_lex_state = 6},
  [9] = {.lex_state = 0, .external_lex_state = 7},
  [10] = {.lex_state = 1, .external_lex_state = 8},
  [11] = {.lex_state = 1, .external_lex_state = 8},
  [12] = {.lex_state = 1, .external_lex_state = 8},
  [13] = {.lex_state = 0, .external_lex_state = 9},
  [14] = {.lex_state = 1, .external_lex_state = 8},
  [15] = {.lex_state = 0, .external_lex_state = 7},
  [16] = {.lex_state = 1, .external_lex_state = 8},
  [17] = {.lex_state = 1, .external_lex_state = 8},
  [18] = {.lex_state = 0, .external_lex_state = 7},
  [19] = {.lex_state = 0, .external_lex_state = 7},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0, .external_lex_state = 10},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 10},
  [28] = {.lex_state = 0, .external_lex_state = 10},
  [29] = {.lex_state = 5, .external_lex_state = 10},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0, .external_lex_state = 10},
  [32] = {.lex_state = 0, .external_lex_state = 10},
  [33] = {.lex_state = 5, .external_lex_state = 10},
  [34] = {.lex_state = 0, .external_lex_state = 10},
  [35] = {.lex_state = 0, .external_lex_state = 10},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0, .external_lex_state = 10},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 10},
  [41] = {.lex_state = 0, .external_lex_state = 10},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0, .external_lex_state = 11},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0, .external_lex_state = 10},
  [49] = {.lex_state = 0, .external_lex_state = 6},
  [50] = {.lex_state = 0, .external_lex_state = 11},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0, .external_lex_state = 12},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 13},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0, .external_lex_state = 12},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 12},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0, .external_lex_state = 10},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tool_directive] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [sym_after] = ACTIONS(1),
    [sym_alias] = ACTIONS(1),
    [sym_all] = ACTIONS(1),
    [sym_architecture] = ACTIONS(1),
    [sym_array] = ACTIONS(1),
    [sym_assert] = ACTIONS(1),
    [sym_attribute] = ACTIONS(1),
    [sym_begin] = ACTIONS(1),
    [sym_block] = ACTIONS(1),
    [sym_buffer] = ACTIONS(1),
    [sym_bus] = ACTIONS(1),
    [sym_case] = ACTIONS(1),
    [sym_component] = ACTIONS(1),
    [sym_configuration] = ACTIONS(1),
    [sym_constant] = ACTIONS(1),
    [sym_context] = ACTIONS(1),
    [sym_default] = ACTIONS(1),
    [sym_disconnect] = ACTIONS(1),
    [sym_downto] = ACTIONS(1),
    [sym_else] = ACTIONS(1),
    [sym_elsif] = ACTIONS(1),
    [sym_end] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [sym_exit] = ACTIONS(1),
    [sym_file] = ACTIONS(1),
    [sym_for] = ACTIONS(1),
    [sym_force] = ACTIONS(1),
    [sym_function] = ACTIONS(1),
    [sym_generate] = ACTIONS(1),
    [sym_generic] = ACTIONS(1),
    [sym_group] = ACTIONS(1),
    [sym_guarded] = ACTIONS(1),
    [sym_if] = ACTIONS(1),
    [sym_impure] = ACTIONS(1),
    [sym_in] = ACTIONS(1),
    [sym_inertial] = ACTIONS(1),
    [sym_inout] = ACTIONS(1),
    [sym_is] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_library] = ACTIONS(1),
    [sym_linkage] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_loop] = ACTIONS(1),
    [sym_map] = ACTIONS(1),
    [sym_new] = ACTIONS(1),
    [sym_next] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_of] = ACTIONS(1),
    [sym_on] = ACTIONS(1),
    [sym_open] = ACTIONS(1),
    [sym_others] = ACTIONS(1),
    [sym_out] = ACTIONS(1),
    [sym_package] = ACTIONS(1),
    [sym_parameter] = ACTIONS(1),
    [sym_port] = ACTIONS(1),
    [sym_postponed] = ACTIONS(1),
    [sym_procedure] = ACTIONS(1),
    [sym_process] = ACTIONS(1),
    [sym_property] = ACTIONS(1),
    [sym_protected] = ACTIONS(1),
    [sym_pure] = ACTIONS(1),
    [sym_range] = ACTIONS(1),
    [sym_record] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_reject] = ACTIONS(1),
    [sym_release] = ACTIONS(1),
    [sym_report] = ACTIONS(1),
    [sym_return] = ACTIONS(1),
    [sym_select] = ACTIONS(1),
    [sym_sequence] = ACTIONS(1),
    [sym_severity] = ACTIONS(1),
    [sym_shared] = ACTIONS(1),
    [sym_signal] = ACTIONS(1),
    [sym_subtype] = ACTIONS(1),
    [sym_then] = ACTIONS(1),
    [sym_transport] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_unaffected] = ACTIONS(1),
    [sym_units] = ACTIONS(1),
    [sym_until] = ACTIONS(1),
    [sym_use] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_vunit] = ACTIONS(1),
    [sym_wait] = ACTIONS(1),
    [sym_when] = ACTIONS(1),
    [sym_while] = ACTIONS(1),
    [sym_with] = ACTIONS(1),
    [sym_attribute_function] = ACTIONS(1),
    [sym_attribute_pure_function] = ACTIONS(1),
    [sym_attribute_range] = ACTIONS(1),
    [sym_attribute_signal] = ACTIONS(1),
    [sym_attribute_subtype] = ACTIONS(1),
    [sym_attribute_type] = ACTIONS(1),
    [sym_attribute_value] = ACTIONS(1),
    [sym_builtin_function] = ACTIONS(1),
    [sym_builtin_type] = ACTIONS(1),
    [sym_operator_adding] = ACTIONS(1),
    [sym_operator_condition] = ACTIONS(1),
    [sym_operator_logical] = ACTIONS(1),
    [sym_operator_miscellaneous] = ACTIONS(1),
    [sym_operator_multiplying] = ACTIONS(1),
    [sym_operator_relational] = ACTIONS(1),
    [sym_operator_shift] = ACTIONS(1),
    [sym_operator_sign] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(51),
    [sym_entity_declaration] = STATE(62),
    [sym_comment] = ACTIONS(3),
    [sym_tool_directive] = ACTIONS(3),
    [sym_entity] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_builtin_type,
    STATE(7), 1,
      sym_mode,
    STATE(12), 1,
      sym_subtype_indication,
    STATE(14), 1,
      sym_type_mark,
    STATE(20), 1,
      sym_resolution_indication,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(9), 5,
      sym_buffer,
      sym_in,
      sym_inout,
      sym_linkage,
      sym_out,
  [30] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_builtin_type,
    STATE(8), 1,
      sym_mode,
    STATE(14), 1,
      sym_type_mark,
    STATE(16), 1,
      sym_subtype_indication,
    STATE(20), 1,
      sym_resolution_indication,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(9), 5,
      sym_buffer,
      sym_in,
      sym_inout,
      sym_linkage,
      sym_out,
  [60] = 9,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_signal,
    STATE(25), 1,
      sym_interface_declaration,
    STATE(29), 1,
      aux_sym_identifier_list_repeat1,
    STATE(44), 1,
      sym_interface_object_declaration,
    STATE(47), 1,
      sym_interface_signal_declaration,
    STATE(55), 1,
      sym_identifier_list,
    STATE(69), 1,
      sym_interface_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [89] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_signal,
    STATE(29), 1,
      aux_sym_identifier_list_repeat1,
    STATE(44), 1,
      sym_interface_object_declaration,
    STATE(46), 1,
      sym_interface_declaration,
    STATE(47), 1,
      sym_interface_signal_declaration,
    STATE(55), 1,
      sym_identifier_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [115] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(19), 2,
      sym_identifier,
      sym_builtin_type,
    ACTIONS(17), 4,
      sym_bus,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
  [130] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_builtin_type,
    STATE(10), 1,
      sym_subtype_indication,
    STATE(14), 1,
      sym_type_mark,
    STATE(20), 1,
      sym_resolution_indication,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [150] = 6,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_builtin_type,
    STATE(12), 1,
      sym_subtype_indication,
    STATE(14), 1,
      sym_type_mark,
    STATE(20), 1,
      sym_resolution_indication,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [170] = 5,
    ACTIONS(21), 1,
      anon_sym_SEMI,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_entity,
    STATE(74), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [187] = 4,
    ACTIONS(29), 1,
      anon_sym_COLON_EQ,
    ACTIONS(31), 1,
      sym_bus,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(27), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [202] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(33), 4,
      sym_bus,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
  [213] = 4,
    ACTIONS(37), 1,
      anon_sym_COLON_EQ,
    ACTIONS(39), 1,
      sym_bus,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(35), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [228] = 5,
    ACTIONS(41), 1,
      sym_begin,
    ACTIONS(43), 1,
      sym_end,
    ACTIONS(45), 1,
      sym_port,
    STATE(50), 1,
      sym_formal_port_clause,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [245] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(47), 4,
      sym_bus,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
  [256] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_SEMI,
    ACTIONS(51), 1,
      sym_entity,
    STATE(70), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [273] = 4,
    ACTIONS(55), 1,
      anon_sym_COLON_EQ,
    ACTIONS(57), 1,
      sym_bus,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(53), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [288] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(17), 4,
      sym_bus,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
  [299] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_SEMI,
    ACTIONS(61), 1,
      sym_entity,
    STATE(66), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [316] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    ACTIONS(65), 1,
      sym_entity,
    STATE(59), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [333] = 3,
    STATE(11), 1,
      sym_type_mark,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(11), 2,
      sym_identifier,
      sym_builtin_type,
  [345] = 4,
    ACTIONS(67), 1,
      anon_sym_SEMI,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_interface_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [359] = 3,
    ACTIONS(73), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(71), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [371] = 4,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(29), 1,
      aux_sym_identifier_list_repeat1,
    STATE(73), 1,
      sym_identifier_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [385] = 3,
    ACTIONS(29), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(27), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [397] = 4,
    ACTIONS(67), 1,
      anon_sym_SEMI,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_interface_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [411] = 3,
    ACTIONS(37), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(35), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [423] = 4,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    STATE(57), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [437] = 4,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    STATE(59), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [451] = 4,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(81), 1,
      sym_identifier,
    STATE(33), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [465] = 4,
    ACTIONS(83), 1,
      anon_sym_SEMI,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_interface_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [479] = 4,
    ACTIONS(21), 1,
      anon_sym_SEMI,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(74), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [493] = 4,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      sym_entity_simple_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [507] = 4,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      sym_identifier,
    STATE(33), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [521] = 3,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(42), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [532] = 3,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(39), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [543] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(95), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [552] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(97), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [561] = 3,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(36), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [572] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(71), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [581] = 3,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(52), 1,
      sym_entity_statement_part,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [592] = 3,
    ACTIONS(93), 1,
      sym_identifier,
    STATE(37), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [603] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(27), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [612] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(101), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [621] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(103), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [630] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(105), 2,
      sym_begin,
      sym_end,
  [639] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(86), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [648] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(107), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [657] = 3,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(67), 1,
      sym_entity_statement_part,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [668] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
    ACTIONS(109), 2,
      sym_identifier,
      sym_builtin_type,
  [677] = 3,
    ACTIONS(111), 1,
      sym_begin,
    ACTIONS(113), 1,
      sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [688] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [696] = 2,
    ACTIONS(117), 1,
      sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [704] = 2,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [712] = 2,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [720] = 2,
    ACTIONS(123), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [728] = 2,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [736] = 2,
    ACTIONS(127), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [744] = 2,
    ACTIONS(129), 1,
      sym_is,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [752] = 2,
    ACTIONS(21), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [760] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [768] = 2,
    ACTIONS(133), 1,
      sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [776] = 2,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [784] = 2,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [792] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [800] = 2,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [808] = 2,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [816] = 2,
    ACTIONS(143), 1,
      sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [824] = 2,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [832] = 2,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [840] = 2,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [848] = 2,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [856] = 2,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [864] = 2,
    ACTIONS(153), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
  [872] = 2,
    ACTIONS(59), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_tool_directive,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 89,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 213,
  [SMALL_STATE(13)] = 228,
  [SMALL_STATE(14)] = 245,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 273,
  [SMALL_STATE(17)] = 288,
  [SMALL_STATE(18)] = 299,
  [SMALL_STATE(19)] = 316,
  [SMALL_STATE(20)] = 333,
  [SMALL_STATE(21)] = 345,
  [SMALL_STATE(22)] = 359,
  [SMALL_STATE(23)] = 371,
  [SMALL_STATE(24)] = 385,
  [SMALL_STATE(25)] = 397,
  [SMALL_STATE(26)] = 411,
  [SMALL_STATE(27)] = 423,
  [SMALL_STATE(28)] = 437,
  [SMALL_STATE(29)] = 451,
  [SMALL_STATE(30)] = 465,
  [SMALL_STATE(31)] = 479,
  [SMALL_STATE(32)] = 493,
  [SMALL_STATE(33)] = 507,
  [SMALL_STATE(34)] = 521,
  [SMALL_STATE(35)] = 532,
  [SMALL_STATE(36)] = 543,
  [SMALL_STATE(37)] = 552,
  [SMALL_STATE(38)] = 561,
  [SMALL_STATE(39)] = 572,
  [SMALL_STATE(40)] = 581,
  [SMALL_STATE(41)] = 592,
  [SMALL_STATE(42)] = 603,
  [SMALL_STATE(43)] = 612,
  [SMALL_STATE(44)] = 621,
  [SMALL_STATE(45)] = 630,
  [SMALL_STATE(46)] = 639,
  [SMALL_STATE(47)] = 648,
  [SMALL_STATE(48)] = 657,
  [SMALL_STATE(49)] = 668,
  [SMALL_STATE(50)] = 677,
  [SMALL_STATE(51)] = 688,
  [SMALL_STATE(52)] = 696,
  [SMALL_STATE(53)] = 704,
  [SMALL_STATE(54)] = 712,
  [SMALL_STATE(55)] = 720,
  [SMALL_STATE(56)] = 728,
  [SMALL_STATE(57)] = 736,
  [SMALL_STATE(58)] = 744,
  [SMALL_STATE(59)] = 752,
  [SMALL_STATE(60)] = 760,
  [SMALL_STATE(61)] = 768,
  [SMALL_STATE(62)] = 776,
  [SMALL_STATE(63)] = 784,
  [SMALL_STATE(64)] = 792,
  [SMALL_STATE(65)] = 800,
  [SMALL_STATE(66)] = 808,
  [SMALL_STATE(67)] = 816,
  [SMALL_STATE(68)] = 824,
  [SMALL_STATE(69)] = 832,
  [SMALL_STATE(70)] = 840,
  [SMALL_STATE(71)] = 848,
  [SMALL_STATE(72)] = 856,
  [SMALL_STATE(73)] = 864,
  [SMALL_STATE(74)] = 872,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_mark, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolution_indication, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 5, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtype_indication, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtype_indication, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 6, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_list, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interface_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interface_list_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 8, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_signal_declaration, 7, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_declaration, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formal_port_clause, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interface_object_declaration, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_simple_name, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 9, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_statement_part, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 8, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 7, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_declaration, 10, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_identifier = 0,
  ts_external_token_after = 1,
  ts_external_token_alias = 2,
  ts_external_token_all = 3,
  ts_external_token_architecture = 4,
  ts_external_token_array = 5,
  ts_external_token_assert = 6,
  ts_external_token_attribute = 7,
  ts_external_token_begin = 8,
  ts_external_token_block = 9,
  ts_external_token_buffer = 10,
  ts_external_token_bus = 11,
  ts_external_token_case = 12,
  ts_external_token_component = 13,
  ts_external_token_configuration = 14,
  ts_external_token_constant = 15,
  ts_external_token_context = 16,
  ts_external_token_default = 17,
  ts_external_token_disconnect = 18,
  ts_external_token_downto = 19,
  ts_external_token_else = 20,
  ts_external_token_elsif = 21,
  ts_external_token_end = 22,
  ts_external_token_entity = 23,
  ts_external_token_exit = 24,
  ts_external_token_file = 25,
  ts_external_token_for = 26,
  ts_external_token_force = 27,
  ts_external_token_function = 28,
  ts_external_token_generate = 29,
  ts_external_token_generic = 30,
  ts_external_token_group = 31,
  ts_external_token_guarded = 32,
  ts_external_token_if = 33,
  ts_external_token_impure = 34,
  ts_external_token_in = 35,
  ts_external_token_inertial = 36,
  ts_external_token_inout = 37,
  ts_external_token_is = 38,
  ts_external_token_label = 39,
  ts_external_token_library = 40,
  ts_external_token_linkage = 41,
  ts_external_token_literal = 42,
  ts_external_token_loop = 43,
  ts_external_token_map = 44,
  ts_external_token_new = 45,
  ts_external_token_next = 46,
  ts_external_token_null = 47,
  ts_external_token_of = 48,
  ts_external_token_on = 49,
  ts_external_token_open = 50,
  ts_external_token_others = 51,
  ts_external_token_out = 52,
  ts_external_token_package = 53,
  ts_external_token_parameter = 54,
  ts_external_token_port = 55,
  ts_external_token_postponed = 56,
  ts_external_token_procedure = 57,
  ts_external_token_process = 58,
  ts_external_token_property = 59,
  ts_external_token_protected = 60,
  ts_external_token_pure = 61,
  ts_external_token_range = 62,
  ts_external_token_record = 63,
  ts_external_token_register = 64,
  ts_external_token_reject = 65,
  ts_external_token_release = 66,
  ts_external_token_report = 67,
  ts_external_token_return = 68,
  ts_external_token_select = 69,
  ts_external_token_sequence = 70,
  ts_external_token_severity = 71,
  ts_external_token_shared = 72,
  ts_external_token_signal = 73,
  ts_external_token_subtype = 74,
  ts_external_token_then = 75,
  ts_external_token_transport = 76,
  ts_external_token_type = 77,
  ts_external_token_unaffected = 78,
  ts_external_token_units = 79,
  ts_external_token_until = 80,
  ts_external_token_use = 81,
  ts_external_token_variable = 82,
  ts_external_token_vunit = 83,
  ts_external_token_wait = 84,
  ts_external_token_when = 85,
  ts_external_token_while = 86,
  ts_external_token_with = 87,
  ts_external_token_attribute_function = 88,
  ts_external_token_attribute_pure_function = 89,
  ts_external_token_attribute_range = 90,
  ts_external_token_attribute_signal = 91,
  ts_external_token_attribute_subtype = 92,
  ts_external_token_attribute_type = 93,
  ts_external_token_attribute_value = 94,
  ts_external_token_builtin_function = 95,
  ts_external_token_builtin_type = 96,
  ts_external_token_operator_adding = 97,
  ts_external_token_operator_condition = 98,
  ts_external_token_operator_logical = 99,
  ts_external_token_operator_miscellaneous = 100,
  ts_external_token_operator_multiplying = 101,
  ts_external_token_operator_relational = 102,
  ts_external_token_operator_shift = 103,
  ts_external_token_operator_sign = 104,
  ts_external_token_error_sentinel = 105,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_identifier] = sym_identifier,
  [ts_external_token_after] = sym_after,
  [ts_external_token_alias] = sym_alias,
  [ts_external_token_all] = sym_all,
  [ts_external_token_architecture] = sym_architecture,
  [ts_external_token_array] = sym_array,
  [ts_external_token_assert] = sym_assert,
  [ts_external_token_attribute] = sym_attribute,
  [ts_external_token_begin] = sym_begin,
  [ts_external_token_block] = sym_block,
  [ts_external_token_buffer] = sym_buffer,
  [ts_external_token_bus] = sym_bus,
  [ts_external_token_case] = sym_case,
  [ts_external_token_component] = sym_component,
  [ts_external_token_configuration] = sym_configuration,
  [ts_external_token_constant] = sym_constant,
  [ts_external_token_context] = sym_context,
  [ts_external_token_default] = sym_default,
  [ts_external_token_disconnect] = sym_disconnect,
  [ts_external_token_downto] = sym_downto,
  [ts_external_token_else] = sym_else,
  [ts_external_token_elsif] = sym_elsif,
  [ts_external_token_end] = sym_end,
  [ts_external_token_entity] = sym_entity,
  [ts_external_token_exit] = sym_exit,
  [ts_external_token_file] = sym_file,
  [ts_external_token_for] = sym_for,
  [ts_external_token_force] = sym_force,
  [ts_external_token_function] = sym_function,
  [ts_external_token_generate] = sym_generate,
  [ts_external_token_generic] = sym_generic,
  [ts_external_token_group] = sym_group,
  [ts_external_token_guarded] = sym_guarded,
  [ts_external_token_if] = sym_if,
  [ts_external_token_impure] = sym_impure,
  [ts_external_token_in] = sym_in,
  [ts_external_token_inertial] = sym_inertial,
  [ts_external_token_inout] = sym_inout,
  [ts_external_token_is] = sym_is,
  [ts_external_token_label] = sym_label,
  [ts_external_token_library] = sym_library,
  [ts_external_token_linkage] = sym_linkage,
  [ts_external_token_literal] = sym_literal,
  [ts_external_token_loop] = sym_loop,
  [ts_external_token_map] = sym_map,
  [ts_external_token_new] = sym_new,
  [ts_external_token_next] = sym_next,
  [ts_external_token_null] = sym_null,
  [ts_external_token_of] = sym_of,
  [ts_external_token_on] = sym_on,
  [ts_external_token_open] = sym_open,
  [ts_external_token_others] = sym_others,
  [ts_external_token_out] = sym_out,
  [ts_external_token_package] = sym_package,
  [ts_external_token_parameter] = sym_parameter,
  [ts_external_token_port] = sym_port,
  [ts_external_token_postponed] = sym_postponed,
  [ts_external_token_procedure] = sym_procedure,
  [ts_external_token_process] = sym_process,
  [ts_external_token_property] = sym_property,
  [ts_external_token_protected] = sym_protected,
  [ts_external_token_pure] = sym_pure,
  [ts_external_token_range] = sym_range,
  [ts_external_token_record] = sym_record,
  [ts_external_token_register] = sym_register,
  [ts_external_token_reject] = sym_reject,
  [ts_external_token_release] = sym_release,
  [ts_external_token_report] = sym_report,
  [ts_external_token_return] = sym_return,
  [ts_external_token_select] = sym_select,
  [ts_external_token_sequence] = sym_sequence,
  [ts_external_token_severity] = sym_severity,
  [ts_external_token_shared] = sym_shared,
  [ts_external_token_signal] = sym_signal,
  [ts_external_token_subtype] = sym_subtype,
  [ts_external_token_then] = sym_then,
  [ts_external_token_transport] = sym_transport,
  [ts_external_token_type] = sym_type,
  [ts_external_token_unaffected] = sym_unaffected,
  [ts_external_token_units] = sym_units,
  [ts_external_token_until] = sym_until,
  [ts_external_token_use] = sym_use,
  [ts_external_token_variable] = sym_variable,
  [ts_external_token_vunit] = sym_vunit,
  [ts_external_token_wait] = sym_wait,
  [ts_external_token_when] = sym_when,
  [ts_external_token_while] = sym_while,
  [ts_external_token_with] = sym_with,
  [ts_external_token_attribute_function] = sym_attribute_function,
  [ts_external_token_attribute_pure_function] = sym_attribute_pure_function,
  [ts_external_token_attribute_range] = sym_attribute_range,
  [ts_external_token_attribute_signal] = sym_attribute_signal,
  [ts_external_token_attribute_subtype] = sym_attribute_subtype,
  [ts_external_token_attribute_type] = sym_attribute_type,
  [ts_external_token_attribute_value] = sym_attribute_value,
  [ts_external_token_builtin_function] = sym_builtin_function,
  [ts_external_token_builtin_type] = sym_builtin_type,
  [ts_external_token_operator_adding] = sym_operator_adding,
  [ts_external_token_operator_condition] = sym_operator_condition,
  [ts_external_token_operator_logical] = sym_operator_logical,
  [ts_external_token_operator_miscellaneous] = sym_operator_miscellaneous,
  [ts_external_token_operator_multiplying] = sym_operator_multiplying,
  [ts_external_token_operator_relational] = sym_operator_relational,
  [ts_external_token_operator_shift] = sym_operator_shift,
  [ts_external_token_operator_sign] = sym_operator_sign,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[14][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_after] = true,
    [ts_external_token_alias] = true,
    [ts_external_token_all] = true,
    [ts_external_token_architecture] = true,
    [ts_external_token_array] = true,
    [ts_external_token_assert] = true,
    [ts_external_token_attribute] = true,
    [ts_external_token_begin] = true,
    [ts_external_token_block] = true,
    [ts_external_token_buffer] = true,
    [ts_external_token_bus] = true,
    [ts_external_token_case] = true,
    [ts_external_token_component] = true,
    [ts_external_token_configuration] = true,
    [ts_external_token_constant] = true,
    [ts_external_token_context] = true,
    [ts_external_token_default] = true,
    [ts_external_token_disconnect] = true,
    [ts_external_token_downto] = true,
    [ts_external_token_else] = true,
    [ts_external_token_elsif] = true,
    [ts_external_token_end] = true,
    [ts_external_token_entity] = true,
    [ts_external_token_exit] = true,
    [ts_external_token_file] = true,
    [ts_external_token_for] = true,
    [ts_external_token_force] = true,
    [ts_external_token_function] = true,
    [ts_external_token_generate] = true,
    [ts_external_token_generic] = true,
    [ts_external_token_group] = true,
    [ts_external_token_guarded] = true,
    [ts_external_token_if] = true,
    [ts_external_token_impure] = true,
    [ts_external_token_in] = true,
    [ts_external_token_inertial] = true,
    [ts_external_token_inout] = true,
    [ts_external_token_is] = true,
    [ts_external_token_label] = true,
    [ts_external_token_library] = true,
    [ts_external_token_linkage] = true,
    [ts_external_token_literal] = true,
    [ts_external_token_loop] = true,
    [ts_external_token_map] = true,
    [ts_external_token_new] = true,
    [ts_external_token_next] = true,
    [ts_external_token_null] = true,
    [ts_external_token_of] = true,
    [ts_external_token_on] = true,
    [ts_external_token_open] = true,
    [ts_external_token_others] = true,
    [ts_external_token_out] = true,
    [ts_external_token_package] = true,
    [ts_external_token_parameter] = true,
    [ts_external_token_port] = true,
    [ts_external_token_postponed] = true,
    [ts_external_token_procedure] = true,
    [ts_external_token_process] = true,
    [ts_external_token_property] = true,
    [ts_external_token_protected] = true,
    [ts_external_token_pure] = true,
    [ts_external_token_range] = true,
    [ts_external_token_record] = true,
    [ts_external_token_register] = true,
    [ts_external_token_reject] = true,
    [ts_external_token_release] = true,
    [ts_external_token_report] = true,
    [ts_external_token_return] = true,
    [ts_external_token_select] = true,
    [ts_external_token_sequence] = true,
    [ts_external_token_severity] = true,
    [ts_external_token_shared] = true,
    [ts_external_token_signal] = true,
    [ts_external_token_subtype] = true,
    [ts_external_token_then] = true,
    [ts_external_token_transport] = true,
    [ts_external_token_type] = true,
    [ts_external_token_unaffected] = true,
    [ts_external_token_units] = true,
    [ts_external_token_until] = true,
    [ts_external_token_use] = true,
    [ts_external_token_variable] = true,
    [ts_external_token_vunit] = true,
    [ts_external_token_wait] = true,
    [ts_external_token_when] = true,
    [ts_external_token_while] = true,
    [ts_external_token_with] = true,
    [ts_external_token_attribute_function] = true,
    [ts_external_token_attribute_pure_function] = true,
    [ts_external_token_attribute_range] = true,
    [ts_external_token_attribute_signal] = true,
    [ts_external_token_attribute_subtype] = true,
    [ts_external_token_attribute_type] = true,
    [ts_external_token_attribute_value] = true,
    [ts_external_token_builtin_function] = true,
    [ts_external_token_builtin_type] = true,
    [ts_external_token_operator_adding] = true,
    [ts_external_token_operator_condition] = true,
    [ts_external_token_operator_logical] = true,
    [ts_external_token_operator_miscellaneous] = true,
    [ts_external_token_operator_multiplying] = true,
    [ts_external_token_operator_relational] = true,
    [ts_external_token_operator_shift] = true,
    [ts_external_token_operator_sign] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_entity] = true,
  },
  [3] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_buffer] = true,
    [ts_external_token_in] = true,
    [ts_external_token_inout] = true,
    [ts_external_token_linkage] = true,
    [ts_external_token_out] = true,
    [ts_external_token_builtin_type] = true,
  },
  [4] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_signal] = true,
  },
  [5] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_bus] = true,
    [ts_external_token_builtin_type] = true,
  },
  [6] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_builtin_type] = true,
  },
  [7] = {
    [ts_external_token_identifier] = true,
    [ts_external_token_entity] = true,
  },
  [8] = {
    [ts_external_token_bus] = true,
  },
  [9] = {
    [ts_external_token_begin] = true,
    [ts_external_token_end] = true,
    [ts_external_token_port] = true,
  },
  [10] = {
    [ts_external_token_identifier] = true,
  },
  [11] = {
    [ts_external_token_begin] = true,
    [ts_external_token_end] = true,
  },
  [12] = {
    [ts_external_token_end] = true,
  },
  [13] = {
    [ts_external_token_is] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_vhdl_external_scanner_create(void);
void tree_sitter_vhdl_external_scanner_destroy(void *);
bool tree_sitter_vhdl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_vhdl_external_scanner_serialize(void *, char *);
void tree_sitter_vhdl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vhdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_vhdl_external_scanner_create,
      tree_sitter_vhdl_external_scanner_destroy,
      tree_sitter_vhdl_external_scanner_scan,
      tree_sitter_vhdl_external_scanner_serialize,
      tree_sitter_vhdl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
