(entity_declaration) @context
(generic_clause) @context
(port_clause) @context
(architecture_body) @context
(function_body) @context
(full_type_declaration) @context
(if_statement) @context
(if) @context
(else) @context
(elsif) @context
(process_statement) @context
(case_statement) @context
(case_statement_alternative) @context
(entity_instantiation) @context
(port_map_aspect) @context
(generic_map_aspect) @context
(if_generate_statement) @context
(for_generate_statement) @context
